# General
abbr e "exit"

# Git
abbr gd "git diff -M"
abbr gdc "git diff --cached"
abbr ga "git add"
abbr gaa "git add --all ."
abbr gbd "git branch -D"
abbr gs "git status"
abbr gc "git commit"
abbr gca "git commit -a -m"
abbr gm "git merge --no-ff"
abbr gpt "git push --tags"
abbr gp "git push"
abbr grh "git reset --hard"
abbr gb "git branch"
abbr gcob "git checkout -b"
abbr gco "git checkout"
abbr gba "git branch -a"
abbr gcp "git cherry-pick"
abbr gl "git log --pretty=format:\"%Cgreen%h%Creset - %Cblue%an%Creset @ %ar : %s\""
abbr gl2 "git log --pretty='format:%Cgreen%h%Creset %an - %s' --graph"
abbr glv "git log --stat"
abbr gpom "git pull origin master"
